### ISSUE TITLE
Support for Key-Value Pair Query Results, Streamed Data Access

### ISSUE THREAD

**Issue by Shanmugavel-J** [databendlabs/bendsql#507]
Currently, the npm databend-driver has the following limitations that impact usability and efficiency:

1.	**Array of Arrays for Results:** Query results are returned as arrays of arrays containing only values. To fetch field names (keys) alongside these values, the same query must be executed again using a different function. This approach is inefficient and cumbersome.
2.	**Variant Types in String Format:** Variant types are returned in string format instead of actual objects or arrays. This requires explicit parsing for each record, adding unnecessary overhead and complexity.
3.	**Lack of Streaming Support:** The absence of streaming options makes handling large datasets inefficient.
4.	**Async Query Execution:** There is no support for asynchronous query execution (e.g., async/await), which is a common pattern in modern database drivers like those for MySQL and Snowflake. 

Ex:- const results = await conn.exec('SELECT * FROM test;');

results = [{ id: 1 }, { id: 2 }]

**Proposed Features:**

1. **Key-Value Pair Rows:** An option to fetch query results as objects with field names (keys) and corresponding values (e.g., JSON format).
2. **Proper Handling of Variant Types:** Return variant types as actual objects or arrays instead of strings to eliminate the need for explicit parsing.
3. **Streaming Support:** Introduce support for streaming query results to efficiently handle large datasets.
4.	**Async Query Execution:** Add methods for executing queries using async/await to align with modern asynchronous programming patterns.

These features would significantly improve the usability, performance, and developer experience of the databend-driver. Thanks!

**Comment by everpcpc** [comment]
Thank you for your detailed feedback on the `npm databend-driver`. We are pleased to inform you that the mentioned limitations have been addressed:

1. **Array of Arrays for Results**: You can now use `row.data()` instead of `row.values()` to fetch query results with field names.
2. **Variant Types in String Format**: Support has been added for returning variant types as actual objects or arrays by setting the parameter `{ variantAsObject: true }` for `row` or `client`.
3. **Lack of Streaming Support**: Our `queryIter()` method already returns rows as a streaming result.
4. **Async Query Execution**: All methods in our Node.js client already support async/await.

We hope these improvements enhance your experience with the `databend-driver`. If you have any further questions or feedback, please feel free to share.

Thank you again for your valuable input!

**Comment by Shanmugavel-J** [comment]
@everpcpc Thanks for your support. We encountered an issue with the output of the record. For example, when we call queryIter or any method to execute a query, the output should ideally be in its respective data type, correct? However, for bigint, the output is returned as '7n' instead of 7 (even though it’s not a very large value). Using the MySQL handler, it provides the correct result. Does the output remain consistent across types—for instance, varchar as a string, and number and boolean in their proper formats? Am I correct?

**Comment by everpcpc** [comment]
@Shanmugavel-J 

Thank you for your feedback. I'd like to clarify the data type mappings between Databend and JavaScript native types. You can find a full list of these mappings in our documentation here: [Databend Driver Type Mapping](https://www.npmjs.com/package/databend-driver?activeTab=readme#type-mapping).

Regarding your specific concern, '7n' is indeed the correct output for bigint in JavaScript. In JavaScript, '7n' represents a BigInt, which is a primitive type. For more details on BigInt, you can refer to the MDN documentation: [BigInt in JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt).

To answer your query about consistency across types:
- varchar is returned as a string.
- number and boolean are returned in their proper formats.
- bigint is returned as a BigInt (e.g., '7n').

This ensures that the output remains consistent and adheres to JavaScript's handling of different data types. If you have any further questions, feel free to ask!

**Comment by Shanmugavel-J** [comment]
@everpcpc Thanks! I indeed knew it but since the mysql handler port gave in a different way which made me ask it.

**Comment by everpcpc** [comment]
@Shanmugavel-J Oh, I see. The type mapping depends on how the driver converts the response from the database. We recommend using the native Databend driver for better support. The MySQL handler is intended for transitional use and is just a compatible implementation. It has not been fully tested, so there may be some corner cases that are not covered.

**Comment by Shanmugavel-J** [comment]
@everpcpc Yes, I noticed the features have been released. I’m now updating to the databend-driver package. Instead of an iterator for streams, I had requested a Node.js Readable stream, similar to what Snowflake and mysql provides.

**Comment by everpcpc** [comment]
@Shanmugavel-J  I get it. We will add support for Node.js Readable stream in upcoming releases, making data streaming operations more flexible and convenient.

**Comment by Shanmugavel-J** [comment]
@everpcpc That sounds great please let me know once that feature is added for fetching the rows in stream format.

Thanks again for your support!!

**Comment by everpcpc** [comment]
@Shanmugavel-J Hi, we have released a new version with Readable stream support. You could refer to the examples: https://www.npmjs.com/package/databend-driver?activeTab=readme#usage

**Comment by Shanmugavel-J** [comment]
@everpcpc I will check and get back to you. Thanks!

**Comment by Shanmugavel-J** [comment]
@everpcpc Please find my below observations,

1. **queryIter** Method

Doc:

```
// get rows of map
const rows = await conn.queryIter("SELECT * FROM test");
let row = await rows.next();
while (row) {
  console.log(row.data());
  row = await rows.next();
}
```

Actually when i execute this. I get rows.next() is not an function. I do get only a single row rather it should ideally provide me all the rows.

```
TypeError: te.next is not a function
```

2. **queryIterExt** Method

When i execute the above method i could see its comment saying the rows, schema & stats could be fetched but i don't get the rows as output when i execute this method but i get the stats (execution time etc). but Ideally it should provide me with the rows, schema & the stats am I correct?

3. **Stream** It works as expected. I can use the nodejs stream in any way right other than that mentioned in the doc ?.

One observation was like, I couldn't see any types for stream. Could you please update it so that it would be great to see what that function would return?

example code:
```
const rows = await conn.queryIter("SELECT * FROM my_table1;");
const stream = rows.stream();
stream.on('data', (data) => {
  console.log(data.data());
});
stream.on('end', async () => {
  console.log('end');
});
stream.on('error', (err) => {
  console.log(err);
});
```

Object (`Variant Data`) one I will try and let you know. Thanks!

**Comment by everpcpc** [comment]
cc @youngsofun please check this error:
> thread '<unnamed>' panicked at core/src/client.rs:894:13:
> there is no reactor running, must be called from the context of a Tokio 1.x runtime
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> thread '<unnamed>' panicked at core/src/panicking.rs:221:5:
> panic in a function that cannot unwind

**Comment by everpcpc** [comment]
Hi, @Shanmugavel-J 

1. We've tested this driver with Node versions 18, 20, and 22, but not with 16 since it is deprecated. However, it might still work with version 16 as it is a native plugin, so feel free to try it out and report any bugs.
2. `queryIterExt` is not intended for customer use, but it is okay to use it. This function returns either a row or statistics with each fetch.
3. `rows.stream()` returns a common implementation for [`node:stream:Readable`](https://nodejs.org/api/stream.html#readable-streams) with `Row` as the item in `objectMode`.
4. This error will be fixed in the next release.

**Comment by Shanmugavel-J** [comment]
@everpcpc Thanks! The variantObject option works as well.
